// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Compress(arg1:main.CompressOptions):Promise<Array<main.CompressResult>>;

export function DownloadFFmpeg():Promise<boolean>;

export function GetVersion():Promise<string>;

export function HasFFmpeg():Promise<boolean>;

export function HasGhostscript():Promise<boolean>;

export function RevealFile(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<main.FileInfo>>;

export function SelectOutputDir():Promise<string>;
