// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasFFmpeg() {
  return window['go']['main']['App']['HasFFmpeg']();
}

export function HasGhostscript() {
  return window['go']['main']['App']['HasGhostscript']();
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
